### ISSUE TITLE
为什么log打印的日志是重复的两条

### ISSUE THREAD

**Issue by lukeyMing** [solely/yaf-quiet#1]
`
public function indexAction()
    {
        echo 'hello world!';
        Log::error('测试warning2', array('error' => 'error', 'second' => 'secondError'));
        dump($_GET);
        dump($this->getRequest()->getParams());
        return false;
    }
`
日志里的结果却是完全相同的两条
[2017-08-29 11:13:11] app.ERROR: 测试warning2 {"error":"error","second":"secondError"} []
[2017-08-29 11:13:11] app.ERROR: 测试warning2 {"error":"error","second":"secondError"} []

抛开封装的Log类，直接调用monolog

`
public function indexAction()
    {
        echo 'hello world!';
        //Log::error('测试warning2', array('error' => 'error', 'second' => 'secondError'));
        $log = new Logger('test');
        $log->pushHandler(new StreamHandler(APPLICATION_PATH.'/log/test.log', Logger::ERROR));
        $log->error('Bar');

        dump($_GET);
        dump($this->getRequest()->getParams());
        return false;
    }
`

日志里同样是两条完全一样的日志

[2017-08-29 11:22:54] test.ERROR: Bar [] []
[2017-08-29 11:22:54] test.ERROR: Bar [] []

通过页面打印的结果来看，indexAction 确实是只执行了一次，请问这个是monolog的问题吗，还是需要其他配置  LINUX环境

**Comment by lukeyMing** [comment]
我修改了 monolog StreamHandler.php 中的write方法，
有一段 $this->stream = fopen($this->url, 'a');
改成了 $this->stream = fopen($this->url, 'ab');
重试 打印变成一条 正常了

**Comment by solely** [comment]
你是用我写的示例执行后在日志里面发现了两条一样的日志记录么？
示例里面我用两个不同的方法记录了同一条日志一次，请注意看下示例。
日志类优化了下，在debug环境下看日志更清爽。

**Comment by lukeyMing** [comment]
不是你的代码的问题  这个问题可以关掉了.......
